install:
	pip3 install --user MyTT
	pip3 install pandas
update:
	python -m pip install --upgrade pip
	pip3 install --user request
	pip3 install --user requests  -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
ubuntu_install:
	sudo apt install python3
	sudo apt install python3-pip
	sudo apt-get install python3-numpy  python3-pandas
bert:
	pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
	pip3 install pytorch_transformers -i https://pypi.douban.com/simple
	pip3 install huggingface_hub
	pip3 install transformers