NAME := haiuser
install:
	npm install -g vsce
	npm install -g mocha
	npm install -g typescript
	npm install -g yo generator-code
	yo code
watch:
	 npm run watch
package:
	vsce package
publish:
	vsce publish
login:
	vsce login a-shares